rename commandlock_test, better docs

diff --git a/commandlock-test b/commandlock-test
--- a/commandlock-test
+++ b/commandlock-test
@@ -1,9 +1,9 @@
 #!/bin/sh
 
-# fixme: extra line at bottom and top of test if ./commandloc_test is run from here instead of /bin
+# fixme: extra line at bottom and top of test if ./commandlock-test is run from here(?) instead of /bin
 
 #echo "[$$] $0 Testing source requirement."
-msg_bang=`commandlock`
+msg_bang=$(commandlock)
 if [ -z "${msg_bang##source_this_file*}" ];
 then
     :
@@ -31,7 +31,7 @@ echo "[$$] $0 in a non-critical section, about to acquire lock"
 . commandlock
 echo "[$$] $0 in a critical section, about to test lock"
 
-commandlock_test && { echo "[$$] $0 ERROR: Locking Failed." ; exit 1 ; } || \
+commandlock-test && { echo "[$$] $0 ERROR: Locking Failed." ; exit 1 ; } || \
     echo "[$$] $0 YOU SHOULD SEE 2 ERROR MESSAGES WITH THE SAME PID != [$$]"
     echo "[$$] $0 You shoud NOT see a message starting with \"unlink: cannot unlink\""
     echo "[$$] $0 Lock test completed."
